# Generated by Django 4.2.16 on 2024-10-08 18:02

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='twitch_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clip',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='clipvote',
            unique_together={('user', 'clip')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='clips_comme_created_357d07_idx'),
        ),
    ]
